name: build_luban

on: 
  push:
    paths: 
      - src/**
      - .github/workflows/build_luban.yml

jobs:
   windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      with:
       dotnet-version: 8.x
    - run: dotnet build src/Luban.sln --configuration Release

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: ./src/Luban/bin/Release/net8.0
        name: Luban
